### ISSUE TITLE
windows bin for Hadoop version 2.10.0

### ISSUE THREAD

**Issue by AyaAshrafSABER** [cdarlint/winutils#10]
I can't find Hadoop bin file for the last version in Hadoop website

**Comment by cdarlint** [comment]
not yet available in this repo

**Comment by zara441** [comment]
i cant find the hadoop 2.10.2 winutils

**Comment by luanchao19990** [comment]
Thank you for your email.We’ll disposal and reply as soon as possible~Best Wishes~
