### ISSUE TITLE
请求博主帮忙编译hadoop2.10

### ISSUE THREAD

**Issue by FlyThroughMountains** [cdarlint/winutils#4]
现在hadoop2.10系列已经发布了，由于我刚刚接触hadoop，对这块的编译还不是很熟悉，总是遇到很多问题，请问您可以帮忙编译一下吗？

**Comment by cdarlint** [comment]
我感觉，刚接触的话，用2.9或者2.7都不错
如果只是刚接触的基础使用，一般不需要精确对应版本，就可以使用
